kibot:
  version: 1
# Look into pcb_replace, looks sick! Also sch_replace

preflight:
  # Warn us about unconnected
  ignore_unconnected: false

  # Do a DRC check
  run_drc: false # (Skip for now)

  # Replace variables
  set_text_variables:
    - name: "revision"
      command: "git describe --abbrev=8 --always --tags"
    - name: "issue"
      command: "date '+%Y-%m-%d'"

outputs:
  - name: "Images"
    comment: "Schematics and media for use in docs"
    type: svg_sch_print

  - name: "3D Models"
    comment: "3D Models for use by the CAD team"
    type: step
