name: Battle Bot Builder

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

jobs:
  KiCAD-Hardware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          # Config file
          config: Hardware/config.kibot.yaml
          # Prefix for output in config file.
          dir: _hardwareOutput

          # Hardware Files
          schema: "Hardware/BattleBot_Motherboard/BattleBot_Motherboard.kicad_sch"
          board: "Hardware/BattleBot_Motherboard/BattleBot_Motherboard.kicad_pcb"

      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: BattleBotHardware
          path: _hardwareOutput
